apiVersion: apps/v1
kind: Deployment
metadata: { name: {{ .Release.Name }} }
spec:
  replicas: {{ .Values.replicaCount }}
  selector: { matchLabels: { app: {{ .Release.Name }} } }
  template:
    metadata: { labels: { app: {{ .Release.Name }} } }
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports: [{ containerPort: 8080 }]
          envFrom:
            - configMapRef: { name: {{ .Release.Name }}-config }
            - secretRef: { name: {{ .Release.Name }}-secret }
          resources: {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe: { httpGet: { path: /actuator/health/readiness, port: 8080 }, initialDelaySeconds: 15 }
          livenessProbe: { httpGet: { path: /actuator/health/liveness, port: 8080 }, initialDelaySeconds: 30 }
